server:
  port: 8082
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      server-addr: 192.168.58.128:8848
      discovery:
        group: ZHX_GROUP
#        namespace: microservice-example
management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon:
  # 请求连接的超时时间 默认的时间为 1 秒
  ConnectTimeout: 10000
  # 请求处理的超时时间
  ReadTimeout: 10000